import type { Dispatch, SetStateAction } from "react";
import type { ClipboardEntry, Locale } from "../../shared/types";

export type StateSetter<T> = Dispatch<SetStateAction<T>>;

export type InstalledAppOption = { label: string; value: string };
export type DefaultAppsMap = Record<string, string>;

export interface AppState {
  showSettings: boolean;
  setShowSettings: StateSetter<boolean>;
  showTagManager: boolean;
  setShowTagManager: StateSetter<boolean>;
  tagManagerEnabled: boolean;
  setTagManagerEnabled: StateSetter<boolean>;
  collapsedGroups: Record<string, boolean>;
  setCollapsedGroups: StateSetter<Record<string, boolean>>;
  history: ClipboardEntry[];
  setHistory: StateSetter<ClipboardEntry[]>;
  search: string;
  setSearch: StateSetter<string>;
  isComposing: boolean;
  setIsComposing: StateSetter<boolean>;
  searchIsFocused: boolean;
  setSearchIsFocused: StateSetter<boolean>;
  showTagFilter: boolean;
  setShowTagFilter: StateSetter<boolean>;
  tagInput: string;
  setTagInput: StateSetter<string>;
  showEmojiPanel: boolean;
  setShowEmojiPanel: StateSetter<boolean>;
  emojiFavorites: string[];
  setEmojiFavorites: StateSetter<string[]>;
  editingTagsId: number | null;
  setEditingTagsId: StateSetter<number | null>;
  revealedIds: Set<number>;
  setRevealedIds: StateSetter<Set<number>>;
  autoStart: boolean;
  setAutoStart: StateSetter<boolean>;
  deduplicate: boolean;
  setDeduplicate: StateSetter<boolean>;
  persistent: boolean;
  setPersistent: StateSetter<boolean>;
  persistentLimitEnabled: boolean;
  setPersistentLimitEnabled: StateSetter<boolean>;
  persistentLimit: number;
  setPersistentLimit: StateSetter<number>;
  appSettings: Record<string, string>;
  setAppSettings: StateSetter<Record<string, string>>;
  defaultApps: DefaultAppsMap;
  setDefaultApps: StateSetter<DefaultAppsMap>;
  installedApps: InstalledAppOption[];
  setInstalledApps: StateSetter<InstalledAppOption[]>;
  dataPath: string;
  setDataPath: StateSetter<string>;
  hotkey: string;
  setHotkey: StateSetter<string>;
  sequentialHotkey: string;
  setSequentialHotkey: StateSetter<string>;
  richPasteHotkey: string;
  setRichPasteHotkey: StateSetter<string>;
  searchHotkey: string;
  setSearchHotkey: StateSetter<string>;
  sequentialMode: boolean;
  setSequentialModeState: StateSetter<boolean>;
  isRecording: boolean;
  setIsRecording: StateSetter<boolean>;
  isRecordingSequential: boolean;
  setIsRecordingSequential: StateSetter<boolean>;
  isRecordingRich: boolean;
  setIsRecordingRich: StateSetter<boolean>;
  isRecordingSearch: boolean;
  setIsRecordingSearch: StateSetter<boolean>;
  deleteAfterPaste: boolean;
  setDeleteAfterPaste: StateSetter<boolean>;
  moveToTopAfterPaste: boolean;
  setMoveToTopAfterPaste: StateSetter<boolean>;
  privacyProtection: boolean;
  setPrivacyProtection: StateSetter<boolean>;
  privacyProtectionKinds: string[];
  setPrivacyProtectionKinds: StateSetter<string[]>;
  privacyProtectionCustomRules: string;
  setPrivacyProtectionCustomRules: StateSetter<string>;
  captureFiles: boolean;
  setCaptureFiles: StateSetter<boolean>;
  captureRichText: boolean;
  setCaptureRichText: StateSetter<boolean>;
  richTextSnapshotPreview: boolean;
  setRichTextSnapshotPreview: StateSetter<boolean>;
  silentStart: boolean;
  setSilentStart: StateSetter<boolean>;
  theme: string;
  setTheme: StateSetter<string>;
  colorMode: string;
  setColorMode: StateSetter<string>;
  showAppBorder: boolean;
  setShowAppBorder: StateSetter<boolean>;
  compactMode: boolean;
  setCompactMode: StateSetter<boolean>;
  clipboardItemFontSize: number;
  setClipboardItemFontSize: StateSetter<number>;
  clipboardTagFontSize: number;
  setClipboardTagFontSize: StateSetter<number>;
  emojiPanelEnabled: boolean;
  setEmojiPanelEnabled: StateSetter<boolean>;
  emojiPanelTab: "emoji" | "favorites";
  setEmojiPanelTab: StateSetter<"emoji" | "favorites">;
  language: Locale;
  setLanguage: StateSetter<Locale>;
  settingsLoaded: boolean;
  setSettingsLoaded: StateSetter<boolean>;
  isWindowPinned: boolean;
  setIsWindowPinned: StateSetter<boolean>;
  registryWinVEnabled: boolean;
  setRegistryWinVEnabled: StateSetter<boolean>;
  showSearchBox: boolean;
  setShowSearchBox: StateSetter<boolean>;
  scrollTopButtonEnabled: boolean;
  setScrollTopButtonEnabled: StateSetter<boolean>;
  arrowKeySelection: boolean;
  setArrowKeySelection: StateSetter<boolean>;
  hideTrayIcon: boolean;
  setHideTrayIcon: StateSetter<boolean>;
  edgeDocking: boolean;
  setEdgeDocking: StateSetter<boolean>;
  followMouse: boolean;
  setFollowMouse: StateSetter<boolean>;
  disableWebviewGpu: boolean;
  setDisableWebviewGpu: StateSetter<boolean>;
  idleDestroyEnabled: boolean;
  setIdleDestroyEnabled: StateSetter<boolean>;
  idleDestroySeconds: number;
  setIdleDestroySeconds: StateSetter<number>;
  customBackground: string;
  setCustomBackground: StateSetter<string>;
  customBackgroundOpacity: number;
  setCustomBackgroundOpacity: StateSetter<number>;
  surfaceOpacity: number;
  setSurfaceOpacity: StateSetter<number>;
  selectedIndex: number;
  setSelectedIndex: StateSetter<number>;
  isKeyboardMode: boolean;
  setIsKeyboardMode: StateSetter<boolean>;
  isLoadingMore: boolean;
  setIsLoadingMore: StateSetter<boolean>;
  hasMore: boolean;
  setHasMore: StateSetter<boolean>;
  currentOffset: number;
  setCurrentOffset: StateSetter<number>;
  soundEnabled: boolean;
  setSoundEnabled: StateSetter<boolean>;
  soundVolume: number;
  setSoundVolume: StateSetter<number>;
  pasteSoundEnabled: boolean;
  setPasteSoundEnabled: StateSetter<boolean>;
  pasteMethod: string;
  setPasteMethod: StateSetter<string>;
  typeFilter: string | null;
  setTypeFilter: StateSetter<string | null>;
}
